services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tripDB
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  book-my-flight-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-my-flight-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tripDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_APPLICATION_NAME: BookMyFlight
      SERVER_PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql-db

volumes:
  mysql_data: