# changing the server port
server:
  port: 3001

spring:
  application:
    name: BookMyFlight
  datasource: # db specific properties
    url: jdbc:mysql://localhost:3306/tripDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa: # ORM software specific properties
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  docker:
    compose:
      enabled: true
#  data:
#    redis:
#      host: localhost
#      port: 6379
#    mongodb:
#      uri: mongodb://user:password@mongodb:27017/tripDB


bookMyBus:
  openapi:
    dev-url: http://localhost:3000
    prod-url: https://bookMyBus-api.com