name: Only Tests
on:
  push:
    branches:
      - main

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-Java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: All tests and coverage check
        run: mvn clean test