name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
      # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main 
      # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 
        # Use Temurin distribution for JDK
			
    - name: Test
      run: ./mvnw clean test

    - name: Build
      run: ./mvnw clean install
    
    - name: Package
      run: mvn clean package --file pom.xml

    # - name: Build Docker image
      # run: docker build -t book-my-flight-latest .
